#Demonstração NumPY 
###Disciplina - Introdução a Ciência de Dados - Univesp
###Videoaula 5
###Prof. Dr. José Eduardo Santarem Segundo

#Importar Biblioteca

In [ ]:
import numpy as np

#Gerar Dados Aleatórios

##Gerar um NDArray de 2x3 (duas lista com 3 elementos)

In [ ]:
dados=np.random.rand(2,3)

In [ ]:
dados

array([[0.46751893, 0.52445558, 0.10204545],
       [0.05423262, 0.1979185 , 0.8055835 ]])

#Tipo do Array

In [ ]:
dados.dtype

dtype('float64')

#Tamanho e quantidade de dimensões

In [ ]:
dados.shape

(2, 3)

In [ ]:
dados.ndim

2

#Criar ndarray usando a função array
##Ao criar o array a função array tenta utilizar o melhor tipo de dado

In [ ]:
lista=[1,2,5,7.8,1.25]

In [ ]:
dados2=np.array(lista)

In [ ]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [ ]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [ ]:
dados3=np.array(lista2)

In [ ]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

#Outras maneiras de criar arrays

In [ ]:
dadoszero=np.zeros(10)

In [ ]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
dadoszero2=np.zeros((2,3))

In [ ]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
dadosum=np.ones(5)

In [ ]:
dadosum

array([1., 1., 1., 1., 1.])

In [ ]:
dadosseq=np.arange(10)

In [ ]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq2=np.arange(0,20,2)

In [ ]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
dadosseq.dtype

dtype('int64')

In [ ]:
dadosseqf=dadosseq.astype(np.float64)

In [ ]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
dadosseqf.dtype

dtype('float64')

#Aritmética com Arrays

In [ ]:
dados4=np.array([[1,2,3],[4,5,6]])

In [ ]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
dados5=dados4+dados4

In [ ]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

#Indexação

In [ ]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
dadosseq[5]

5

## Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de bando de dados. 
##Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [ ]:
dadosseq[3:6]

array([3, 4, 5])

In [ ]:
dadosseq[3:6]=20

In [ ]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [ ]:
fatiadados=dadosseq[2:4]

In [ ]:
fatiadados

array([ 2, 20])

In [ ]:
fatiadados[1]=2000

In [ ]:
fatiadados

array([   2, 2000])

In [ ]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [ ]:
fatiadados[:]=333

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Copiar dados

In [ ]:
fatia2=dadosseq[2:4].copy()

In [ ]:
fatia2

array([333, 333])

In [ ]:
fatia2[:]=111

In [ ]:
fatia2

array([111, 111])

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Array com mais de uma dimensão

In [ ]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dados6[1,2]

6

#Máscaras

In [ ]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [ ]:
mascara=(dadosseq<100)

In [ ]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
dadosseq[dadosseq<20]=8888

In [ ]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

#Transposição

In [ ]:
dados7=np.arange(15).reshape((3,5))

In [ ]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#Multiplicação de Matrizes com Dots

In [ ]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

# Vejam que há muitas outras funções que podem ser exploradas como: sin, cos, power, mod, sqrt entre outros